"""Deterministic synthetic interference injection and masking.

Scope boundary -- read this before using anything here.

This module demonstrates a **software** strategy on **synthetic** interference
that this package itself injected. It does not claim scientifically validated
radio-frequency-interference removal, and it does not claim signal preservation
on any real observation. No measured spectrum is involved at any point.

The cleaner is conservative by construction: it replaces only the channels it
flags, records every flagged channel, and leaves every other sample bitwise
untouched.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .config import CleaningConfig, InterferenceConfig
from .errors import InterferenceError
from .spectrum import SYNTHETIC_LABEL, Spectrum

#: Scale factor converting a median absolute deviation to a Gaussian-equivalent sigma.
MAD_TO_SIGMA = 1.4826


@dataclass(frozen=True)
class InjectionResult:
    """A synthetic spectrum with injected interference, and the channels it touched."""

    spectrum: Spectrum
    injected_indices: np.ndarray


@dataclass(frozen=True)
class CleaningResult:
    """A cleaned synthetic spectrum together with the explicit mask of altered samples."""

    spectrum: Spectrum
    mask: np.ndarray
    altered_indices: np.ndarray
    original_volts: np.ndarray
    threshold_sigma: float
    window_channels: int

    @property
    def n_masked(self) -> int:
        """Number of channels the cleaner flagged."""
        return int(self.mask.sum())

    def write_mask(self, path: Path) -> None:
        """Write the explicit mask record as a deterministic, labelled CSV file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        header = [
            f"# {SYNTHETIC_LABEL} interference mask generated by galaxy-structure; "
            "not an observation.",
            f"# threshold_sigma: {self.threshold_sigma!r}",
            f"# window_channels: {self.window_channels}",
            f"# masked_channels: {self.n_masked}",
            "# Every channel listed below was replaced by the cleaner. Every channel that is "
            "not listed is bitwise identical to the input.",
        ]
        with path.open("w", encoding="utf-8", newline="\n") as handle:
            for line in header:
                handle.write(line + "\n")
            writer = csv.writer(handle, lineterminator="\n")
            writer.writerow(["channel_index", "frequency_hz", "original_volts", "cleaned_volts"])
            for index in np.flatnonzero(self.mask):
                writer.writerow(
                    [
                        int(index),
                        repr(float(self.spectrum.frequency_hz[index])),
                        repr(float(self.original_volts[index])),
                        repr(float(self.spectrum.amplitude_volts[index])),
                    ]
                )


def _nearest_channel(frequency_hz: np.ndarray, target_hz: float) -> int:
    return int(np.argmin(np.abs(frequency_hz - target_hz)))


def inject_interference(spectrum: Spectrum, config: InterferenceConfig) -> InjectionResult:
    """Add the configured deterministic narrow-band features to ``spectrum``.

    Only amplitudes change; the frequency axis is never modified.
    """
    amplitude = spectrum.amplitude_volts.copy()
    touched: set[int] = set()

    for spike in config.spikes:
        if not (spectrum.frequency_hz[0] <= spike.center_hz <= spectrum.frequency_hz[-1]):
            raise InterferenceError(
                f"spike center {spike.center_hz!r} Hz does not lie within the spectrum band "
                f"[{spectrum.frequency_hz[0]!r}, {spectrum.frequency_hz[-1]!r}] Hz."
            )
        center = _nearest_channel(spectrum.frequency_hz, spike.center_hz)
        half = spike.width_channels // 2
        start = center - half
        stop = center + half
        if start < 0 or stop >= spectrum.n_channels:
            raise InterferenceError(
                f"spike of width {spike.width_channels} channels centred on channel {center} "
                "extends past the edge of the spectrum."
            )
        for index in range(start, stop + 1):
            amplitude[index] += spike.amplitude_volts
            touched.add(index)

    return InjectionResult(
        spectrum=spectrum.with_amplitude(amplitude),
        injected_indices=np.array(sorted(touched), dtype=np.int64),
    )


def _median_filter(values: np.ndarray, window: int) -> np.ndarray:
    half = window // 2
    padded = np.pad(values, half, mode="edge")
    windows = np.lib.stride_tricks.sliding_window_view(padded, window)
    return np.median(windows, axis=-1)


def clean_interference(spectrum: Spectrum, config: CleaningConfig) -> CleaningResult:
    """Flag and replace channels that stand above a robust local baseline.

    The baseline is a running median over ``window_channels``; the scatter is a
    median-absolute-deviation estimate of the residual. A channel is flagged when
    its positive residual exceeds ``threshold_sigma`` times that scatter, and a
    flagged channel is replaced by its local median. Unflagged channels are
    copied through bitwise unchanged.
    """
    if config.window_channels > spectrum.n_channels:
        raise InterferenceError(
            f"cleaning window of {config.window_channels} channels is wider than the "
            f"{spectrum.n_channels}-channel spectrum."
        )

    original = spectrum.amplitude_volts
    baseline = _median_filter(original, config.window_channels)
    residual = original - baseline
    scatter = MAD_TO_SIGMA * float(np.median(np.abs(residual)))

    if scatter > 0.0:
        mask = residual > config.threshold_sigma * scatter
    else:
        # A degenerate spectrum gives the robust estimator no scatter to compare
        # against. Flagging on any positive residual would then remove ordinary
        # curvature, so nothing is flagged and nothing is altered.
        mask = np.zeros(spectrum.n_channels, dtype=bool)

    cleaned = original.copy()
    cleaned[mask] = baseline[mask]
    altered = np.flatnonzero(cleaned != original)

    return CleaningResult(
        spectrum=spectrum.with_amplitude(cleaned),
        mask=mask,
        altered_indices=altered.astype(np.int64),
        original_volts=original,
        threshold_sigma=config.threshold_sigma,
        window_channels=config.window_channels,
    )
