"""Run-manifest construction and validation.

The manifest is the record of what a run produced: the configuration and its
checksum, the seed, the pinned package versions, the command template, and a
SHA-256 for every generated artifact. Every artifact entry carries the word
``synthetic``.

The manifest deliberately records **no absolute path, host name, user name, or
timestamp**, so that two runs of the same configuration in different output
directories produce byte-identical manifests within one pinned environment.
"""

from __future__ import annotations

import hashlib
import json
import platform
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _version
from pathlib import Path
from typing import Any

from .config import DemoConfig, config_checksum
from .errors import ManifestError
from .spectrum import SYNTHETIC_LABEL
from .velocity import (
    ASTROPY_DOPPLER_REFERENCE_URL,
    NIST_HYDROGEN_REFERENCE_URL,
    NO_REFERENCE_FRAME,
)

#: The only manifest schema this package writes or validates.
MANIFEST_VERSION = 1

#: Recorded verbatim; the concrete directory and seed are never written down.
COMMAND_TEMPLATE = "galaxy-structure run-demo --output-dir OUTPUT_DIR --seed SEED"

#: Packages whose versions are recorded for every run.
RECORDED_PACKAGES = ("galaxy-structure", "numpy", "astropy", "matplotlib")

#: Boundary statements copied into every manifest.
BOUNDARIES = (
    "Every datum in this run is synthetic and generated by this package; no measured "
    "observation is read, shipped, or reproduced.",
    "No rotation curve, galactic-structure result, calibration accuracy, uncertainty, "
    "detection, or agreement-with-literature quantity is produced or claimed.",
    "No observational reference-frame correction is applied; the velocity coordinate is not "
    "topocentric, geocentric, barycentric, heliocentric, or LSR.",
    "The Doppler convention and rest frequency are a synthetic-demonstration convention, not a "
    "validated method for any measurement.",
)

_CHUNK = 1024 * 1024


def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        while chunk := handle.read(_CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def _package_versions() -> dict[str, str]:
    versions: dict[str, str] = {"python": platform.python_version()}
    for name in RECORDED_PACKAGES:
        try:
            versions[name] = _version(name)
        except PackageNotFoundError:  # pragma: no cover - dependency always installed
            versions[name] = "unknown"
    return versions


def build_manifest(
    *,
    config: DemoConfig,
    output_dir: Path,
    artifacts: dict[str, str],
    descriptions: dict[str, str],
) -> dict[str, Any]:
    """Build the manifest mapping for a completed run.

    Args:
        config: The validated configuration the run used.
        output_dir: Directory holding the artifacts. Its name is never recorded.
        artifacts: Mapping of artifact key to output-relative POSIX path.
        descriptions: Mapping of artifact key to a one-line description.
    """
    output_dir = Path(output_dir)
    entries = []
    for key in sorted(artifacts, key=lambda name: artifacts[name]):
        relative = artifacts[key]
        path = output_dir / relative
        if not path.is_file():
            raise ManifestError(f"cannot record a missing artifact: {relative}")
        entries.append(
            {
                "key": key,
                "path": relative,
                "description": descriptions[key],
                "label": SYNTHETIC_LABEL,
                "sha256": sha256_file(path),
                "bytes": path.stat().st_size,
            }
        )

    return {
        "manifest_version": MANIFEST_VERSION,
        "package": "galaxy-structure",
        "label": SYNTHETIC_LABEL,
        "seed": config.seed,
        "command_template": COMMAND_TEMPLATE,
        "configuration": config.to_mapping(),
        "configuration_checksum": config_checksum(config),
        "package_versions": _package_versions(),
        "reference_frame": NO_REFERENCE_FRAME,
        "reference_documentation": {
            "rest_frequency": NIST_HYDROGEN_REFERENCE_URL,
            "doppler_convention": ASTROPY_DOPPLER_REFERENCE_URL,
        },
        "boundaries": list(BOUNDARIES),
        "artifacts": entries,
    }


def write_manifest(manifest: dict[str, Any], path: Path) -> None:
    """Write the manifest deterministically: fixed indentation, trailing newline."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")


def read_manifest(path: Path) -> dict[str, Any]:
    """Read and minimally check a manifest file."""
    path = Path(path)
    if not path.is_file():
        raise ManifestError(f"manifest does not exist: {path.name}")
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ManifestError(f"{path.name} is not valid JSON: {error.msg}") from error
    if not isinstance(manifest, dict) or "artifacts" not in manifest:
        raise ManifestError(f"{path.name} is not a galaxy-structure run manifest.")
    if manifest.get("manifest_version") != MANIFEST_VERSION:
        raise ManifestError(
            f"unsupported manifest_version {manifest.get('manifest_version')!r}; this package "
            f"understands {MANIFEST_VERSION}."
        )
    return manifest


def validate_manifest(output_dir: Path, manifest_name: str = "manifest.json") -> dict[str, Any]:
    """Validate that ``output_dir`` holds exactly the artifacts its manifest records.

    Raises:
        ManifestError: If the manifest is absent or malformed, an artifact is
            missing, an artifact's checksum differs, or an unexpected extra file
            is present.
    """
    output_dir = Path(output_dir)
    manifest = read_manifest(output_dir / manifest_name)

    recorded = {entry["path"] for entry in manifest["artifacts"]}
    present = {
        path.relative_to(output_dir).as_posix()
        for path in output_dir.rglob("*")
        if path.is_file() and path.name != manifest_name
    }

    missing = sorted(recorded - present)
    if missing:
        raise ManifestError(f"artifact(s) missing from {output_dir.name}: {', '.join(missing)}")
    unexpected = sorted(present - recorded)
    if unexpected:
        raise ManifestError(
            f"unexpected file(s) not recorded in the manifest: {', '.join(unexpected)}"
        )

    for entry in manifest["artifacts"]:
        path = output_dir / entry["path"]
        actual = sha256_file(path)
        if actual != entry["sha256"]:
            raise ManifestError(
                f"checksum mismatch for {entry['path']}: manifest records "
                f"{entry['sha256'][:12]}..., file hashes to {actual[:12]}..."
            )
        if path.stat().st_size != entry["bytes"]:
            raise ManifestError(f"size mismatch for {entry['path']}.")

    return manifest
